/* =========================================================
   Query เช็คว่า ACC_NO หายไปจาก table ไหน
   ใช้ PARALLEL hint เพื่อเพิ่มความเร็ว
   ========================================================= */
SELECT /*+ PARALLEL(32) */
    bc.ACC_NO,
    CASE WHEN ar.ACC_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน MV_DMS_ACC_REPORT",
    CASE WHEN c.CID IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน CONTRACT",
    CASE WHEN rb.BANK_CODE IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน RDBBANK",
    CASE WHEN rsm.ACC_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน REPORT_SUMMARY_MONTH",
    CASE WHEN la.ACC_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน LOAN_ACCOUNT",
    CASE WHEN fr.ACCOUNT_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน DMS_TRN_INPUT_FOR_RECAL",
    CASE WHEN tbs.ACCOUNT_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน DMS_TRN_BILL_SUMMARY",
    CASE WHEN tid.ACCOUNT_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน DMS_TRN_CAL_INT_ADD_DAY",
    CASE WHEN ktb.ACC_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน MV_KTB_DAY_15_01_2026",
    CASE WHEN tb.ACCOUNT_NO IS NULL THEN 'X' ELSE '' END AS "ไม่พบใน bills_summary"
FROM PGETMP.LIST_ACC_BROKEN_CONTRACT bc

LEFT JOIN DMS.MV_DMS_ACC_REPORT ar 
    ON bc.ACC_NO = ar.ACC_NO

LEFT JOIN DMSDBA.CONTRACT c 
    ON ar.CID = c.CID

LEFT JOIN DMSDBA.RDBBANK rb 
    ON c.STU_BANK_CODE = rb.BANK_CODE

LEFT JOIN DMSDBA.REPORT_SUMMARY_MONTH rsm 
    ON ar.ACC_NO = rsm.ACC_NO

LEFT JOIN DMSDBA.LOAN_ACCOUNT la 
    ON bc.ACC_NO = la.ACC_NO

LEFT JOIN DMS.DMS_TRN_INPUT_FOR_RECAL fr 
    ON bc.ACC_NO = fr.ACCOUNT_NO

LEFT JOIN DMS.DMS_TRN_BILL_SUMMARY tbs 
    ON bc.ACC_NO = tbs.ACCOUNT_NO

LEFT JOIN DMS.DMS_TRN_CAL_INT_ADD_DAY tid 
    ON bc.ACC_NO = tid.ACCOUNT_NO

LEFT JOIN DMS.MV_KTB_DAY_15_01_2026 ktb 
    ON bc.ACC_NO = ktb.ACC_NO

LEFT JOIN (
    SELECT DISTINCT ACCOUNT_NO 
    FROM DMS.DMS_TRN_BILLS 
    WHERE STATUS = '1' AND CLOSED_DATE IS NULL
) tb ON ar.ACC_NO = tb.ACCOUNT_NO

WHERE ar.ACC_NO IS NULL
   OR c.CID IS NULL
   OR rsm.ACC_NO IS NULL
   OR la.ACC_NO IS NULL
   OR fr.ACCOUNT_NO IS NULL
   OR tbs.ACCOUNT_NO IS NULL
   OR tid.ACCOUNT_NO IS NULL
   OR ktb.ACC_NO IS NULL;
